### PR TITLE
Unpin Mingo

### LINKED ISSUE #125: Vanilla NodeJS require no longer works in v2.5.1
https://github.com/share/sharedb-mingo-memory/blob/81b5c3ba0434e231e4a7f5219ef9ddb783d96f52/index.js#L1

This type of import now breaks w/ the latest patch.

**Repro:**

```
const mingo = require('mingo')
console.log(mingo)
```

```
❯ node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'mingo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/dzhu/lever/tmp-lol/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### PR DESCRIPTION
**Pull request by hdavidzhu**
`mingo@2.5.2` fixes https://github.com/kofrasa/mingo/issues/125, which caused our builds to fail. Now that the fix is out, let's unpin from `mingo@2.5.0`.

### CODE REVIEW

**Comment by hdavidzhu** [comment]
@ericyhwang Did you push lever's `sharedb-mingo-memory`? Is that what's causing the conflict?

**Comment by ericyhwang** [comment]
The commit SHAs on the branch are different from the commit SHAs on share:master.

Did you [sync the fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) before creating that branch?

**Comment by hdavidzhu** [comment]
Ah good catch, thanks!
